### ISSUE TITLE
Installation failed with Laravel 6.6.0

### ISSUE THREAD

**Issue by miraklasiaf** [nafiesl/SimpleCrudGenerator#17]
$ composer require luthfi/simple-crud-generator --dev
Using version ^1.3 for luthfi/simple-crud-generator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.6.0
    - Conclusion: don't install laravel/framework v6.6.0
    - luthfi/simple-crud-generator 1.3.0 requires illuminate/support 5.5.* || 5.6.* || 5.7.* || 5.8.* -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - luthfi/simple-crud-generator 1.3.1 requires illuminate/support 5.8.* -> satisfiable by illuminate/support[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - laravel/browser-kit-testing v5.0.0 requires illuminate/http ~5.7.0 -> satisfiable by illuminate/http[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - laravel/browser-kit-testing v5.1.0 requires illuminate/http ~5.7.0|~5.8.0 -> satisfiable by illuminate/http[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - laravel/browser-kit-testing v5.1.1 requires illuminate/http ~5.7.0|~5.8.0 -> satisfiable by illuminate/http[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - laravel/browser-kit-testing v5.1.2 requires illuminate/http ~5.7.0|~5.8.0 -> satisfiable by illuminate/http[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/support 5.5.x-dev|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.0|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.16|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.17|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.2|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.28|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.33|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.34|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.35|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.36|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.37|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.39|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.40|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.41|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.43|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.5.44|don't install laravel/framework v6.6.0
    - don't install illuminate/support 5.6.x-dev|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.0|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.1|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.10|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.11|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.12|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.13|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.14|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.15|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.16|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.17|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.19|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.2|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.20|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.21|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.22|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.23|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.24|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.25|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.26|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.27|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.28|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.29|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.3|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.30|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.31|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.32|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.33|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.34|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.35|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.36|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.37|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.38|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.39|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.4|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.5|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.6|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.7|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.8|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.6.9|don't install laravel/framework v6.6.0
    - don't install illuminate/support 5.7.17|don't install laravel/framework v6.6.0
    - don't install illuminate/support 5.7.18|don't install laravel/framework v6.6.0
    - don't install illuminate/support 5.7.19|don't install laravel/framework v6.6.0
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.0|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.1|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.10|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.11|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.15|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.2|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.20|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.21|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.22|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.23|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.26|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.27|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.28|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.3|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.4|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.5|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.6|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.7|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.8|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.7.9|don't install laravel/framework v6.6.0
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.0|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.11|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.12|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.14|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.15|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.17|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.18|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.19|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.2|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.20|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.22|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.24|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.27|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.28|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.29|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.3|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.30|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.31|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.32|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.33|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.34|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.35|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.4|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.8|don't install laravel/framework v6.6.0
    - don't install illuminate/support v5.8.9|don't install laravel/framework v6.6.0
    - don't install illuminate/http 5.7.17|don't install laravel/framework v6.6.0
    - don't install illuminate/http 5.7.18|don't install laravel/framework v6.6.0
    - don't install illuminate/http 5.7.19|don't install laravel/framework v6.6.0
    - don't install illuminate/http 5.7.x-dev|don't install laravel/framework v6.6.0
    - don't install illuminate/http 5.8.x-dev|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.0|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.1|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.10|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.11|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.15|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.2|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.20|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.21|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.22|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.23|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.26|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.27|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.28|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.3|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.4|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.5|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.6|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.7|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.8|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.7.9|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.0|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.11|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.12|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.14|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.15|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.17|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.18|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.19|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.2|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.20|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.22|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.24|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.27|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.28|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.29|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.3|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.30|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.31|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.32|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.33|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.34|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.35|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.4|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.8|don't install laravel/framework v6.6.0
    - don't install illuminate/http v5.8.9|don't install laravel/framework v6.6.0
    - Installation request for laravel/framework (locked at v6.6.0, required as ^6.2) -> satisfiable by laravel/framework[v6.6.0].
    - Conclusion: don't install luthfi/simple-crud-generator 1.3.2|remove symfony/css-selector v5.0.0|install laravel/browser-kit-testing v5.0.0|install laravel/browser-kit-testing v5.1.0|install laravel/browser-kit-testing v5.1.1|install laravel/browser-kit-testing v5.1.2
    - Conclusion: don't install luthfi/simple-crud-generator 1.3.2|don't install symfony/css-selector v5.0.0|install laravel/browser-kit-testing v5.0.0|install laravel/browser-kit-testing v5.1.0|install laravel/browser-kit-testing v5.1.1|install laravel/browser-kit-testing v5.1.2
    - Installation request for luthfi/simple-crud-generator ^1.3 -> satisfiable by luthfi/simple-crud-generator[1.3.0, 1.3.1, 1.3.2].
    - luthfi/simple-crud-generator 1.3.2 requires laravel/browser-kit-testing ^5.0 -> satisfiable by laravel/browser-kit-testing[5.0.x-dev, v5.0.0, v5.1.0, v5.1.1, v5.1.2, v5.1.3].
    - laravel/browser-kit-testing 5.0.x-dev requires symfony/css-selector ^4.2 -> satisfiable by symfony/css-selector[4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1].
    - laravel/browser-kit-testing v5.1.3 requires symfony/css-selector ^4.2 -> satisfiable by symfony/css-selector[4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1].
    - Can only install one of: symfony/css-selector[4.2.x-dev, v5.0.0].
    - Can only install one of: symfony/css-selector[4.3.x-dev, v5.0.0].
    - Can only install one of: symfony/css-selector[4.4.x-dev, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.0, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.0-BETA1, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.0-BETA2, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.0-RC1, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.1, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.10, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.11, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.12, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.2, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.3, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.4, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.5, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.6, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.7, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.8, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.2.9, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.0, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.0-BETA1, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.0-BETA2, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.0-RC1, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.1, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.2, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.3, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.4, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.5, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.6, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.7, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.3.8, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.4.0, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.4.0-BETA1, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.4.0-BETA2, v5.0.0].
    - Can only install one of: symfony/css-selector[v4.4.0-RC1, v5.0.0].
    - Installation request for symfony/css-selector (locked at v5.0.0) -> satisfiable by symfony/css-selector[v5.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by nafiesl** [comment]
Hi @miraklasiaf, thanks for the info, I have managed to reproduce the same error. Looks like it's a dependency problem. Let me check.

**Comment by nafiesl** [comment]
Hi @miraklasiaf, I found that this error caused by the dependency issue on browserkit test for current laravel 6.x. I have reported it here https://github.com/laravel/browser-kit-testing/issues/113. We need to wait their response to resolve this.

**Comment by nafiesl** [comment]
There was a PR that might fix this issue. https://github.com/laravel/browser-kit-testing/pull/114. I have verified it works.

**Comment by miraklasiaf** [comment]
> There was a PR that should fix this issue. [laravel/browser-kit-testing#114](https://github.com/laravel/browser-kit-testing/pull/114). I have verified it works.

Thanks

**Comment by nafiesl** [comment]
This PR https://github.com/laravel/browser-kit-testing/pull/114 has been merged to browserkit's 5.0 branch. I have tested that simple-crud-generator package dependency issue has been resolved, too.

@miraklasiaf, could you please verify?
```bash
$ laravel new laravel6x
$ composer require luthfi/simple-crud-generator --dev
```
If the package installation successful, please close this PR.

Thanks a lot @miraklasiaf, for reporting this issue.

**Comment by miraklasiaf** [comment]
> This PR [laravel/browser-kit-testing#114](https://github.com/laravel/browser-kit-testing/pull/114) has been merged to browserkit's 5.0 branch. I have tested that simple-crud-generator package dependency issue has been resolved, too.
> 
> @miraklasiaf, could you please verify?
> 
> ```shell
> $ laravel new laravel6x
> $ composer require luthfi/simple-crud-generator --dev
> ```
> 
> If the package installation successful, please close this PR.
> 
> Thanks a lot @miraklasiaf, for reporting this issue.

Dependency problem still exists because PR for this issue has been reverted https://github.com/laravel/browser-kit-testing/pull/114#issuecomment-569267903

**Comment by nafiesl** [comment]
Yes @miraklasiaf, I have seen the revert, so our issue still occurs. Lets find the root cause why it needs the symfony 5.0 component.

**Comment by nafiesl** [comment]
@miraklasiaf I have found the root cause, I wrote it here https://github.com/laravel/browser-kit-testing/issues/113#issuecomment-569415591. So the solution is to install symfony/css-selector 4 as our laravel project dependency.

We can try to install this package this way.
```
$ laravel new laravel6x
$ composer require symfony/css-selector:^4.0
$ composer require luthfi/simple-crud-generator --dev
```
I have tried it and got this package successfully installed. Can you verify that it also works on your end, @miraklasiaf?


Thanks.

**Comment by miraklasiaf** [comment]
@nafiesl Yes it works. Thanks!
